Add a design docs page
prometheus/docs pull request #1961
Opened 2021-05-28 22:49 UTC by roidelapluie

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

2021-05-28 23:09 UTC, roidelapluie commented
I will add more design docs once we agree on the principle.

2021-05-28 23:17 UTC, RichiH commented
I think the thing is good, just those nits.

Sent by mobile; please excuse my brevity.

On Sat, May 29, 2021, 01:09 Julien Pivotto ***@***.***> wrote:

> I will add more design docs once we agree on the principle.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/prometheus/docs/pull/1961#issuecomment-850714709>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFYII4ZC2UTYMHSW3FSO33TQAPDPANCNFSM45XTOQTQ>
> .
>

2021-05-31 17:31 UTC, beorn7 commented
Looks great in general.

Do you want to fill in more design docs here right now? Or do that in later PRs?

2021-05-31 21:19 UTC, beorn7 commented
In case it's useful, here my brainstorm:
* prometheus/client_java & micrometer (status: under review, I guess): https://docs.google.com/document/d/1vROky2aIw3kAllfi95gwDJy5P2DyWnCihsjPXGpLwwo/edit# 
* Configuration handling in exporters and Prometheus 3.x (status: under review): https://docs.google.com/document/d/1BK_Gc3ixoWyxr9F5qGC07HEcfDPtb6z96mfqoGyz52Y/edit#heading=h.zcana55kzmxi
* http_sd_configs (status: under review, being implemented): https://docs.google.com/document/d/1tVeuzjpU4-TiYPNWJXKmcyIuZF6A2tUq270RbBT5zho/edit
* Prom Agent (status: approved, more or less, and being implemented): https://docs.google.com/document/d/1cCcoFgjDFwU2n823tKuMvrIhzHty4UDyn0IcfUHiyyI/edit
* Sparse high-resolution histograms (status: approved): https://docs.google.com/document/d/1cLNv3aufPZb3fNfaJgdaRBZsInZKKIHo9E6HinJVbpM/edit
* OpenMetrics transition (status: TODO): (as per dev-summit consensus: "We will create a design document exploring upgrade paths.")
* Metadata (status: empty, oops): https://docs.google.com/document/d/1XiZePSjwU4X5iaIgCIvLzljJzl8lRAdvputuborUcaQ/edit
* topk/bottomk aggregation over time (status: implemented): https://docs.google.com/document/d/1uSbD3T2beM-iX4-Hp7V074bzBRiRNlqUdcWP6JTDQSs/edit
* Semantics of muting in Alertmanager (status: TODO): (as per dev-summit consensus: "We will create a document for the community to collect current pain points and desired behaviour"
* First-class network monitoring support in the Prometheus & Grafana ecosystem (status: under review): https://docs.google.com/document/d/1oEpjiWfTHF352NCAOGolwij3EIkrprCkdQmaQMpjg4M/edit
* Persist Retroactive Rules (status: approved, partially implemented): https://docs.google.com/document/d/16s_-RxYwQYcb4G4mvpmjPolEbD24o54a1LPqJ538Vhc/edit
* TSDB Head Improvements (status: implemented, at least partially, or all? paging @codesome ): https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit# and https://docs.google.com/document/d/1pnEsxB0CDLOxQipGw_vhkJpoDZfZPs_KjqCriumDAXQ/edit

(This is not meant to be a complete list. ;)

2021-06-01 10:49 UTC, beorn7 commented
* Secure Alertmanager cluster traffic (status: being implemented in https://github.com/prometheus/alertmanager/pull/2237): https://github.com/prometheus/alertmanager/blob/master/doc/design/secure-cluster-traffic.md

2021-06-01 11:35 UTC, codesome commented
> TSDB Head Improvements (status: implemented, at least partially, or all? paging @codesome ): https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit# and https://docs.google.com/document/d/1pnEsxB0CDLOxQipGw_vhkJpoDZfZPs_KjqCriumDAXQ/edit


Only the m-mapping of "full" chunks is done among them. The idea about "partial chunks" is in-progress (the [snapshot PR](https://github.com/prometheus/prometheus/pull/7229)).

Plus, everything in that doc is not planned to be implemented (for example the number 5 in second doc about series and tombstones). And the doc might/will not be 100% in sync with what was finally implemented or being implemented.

2021-06-01 13:04 UTC, beorn7 commented
Thanks @codesome . 

I guess a certain degree of "we did this differently after all" is inherent to most design docs. So I don't think we have to call that out explicitly (but perhaps it's worth mentioning in the preamble on this page?).

2021-06-07 17:34 UTC, beorn7 requested changes
Thanks for adding all those links to the table.

I found a few syntax issues, see comments.

In different news: Are you aware that we can use markdown tables on the site? See https://github.com/prometheus/docs/blob/master/content/docs/practices/histograms.md .

2021-06-07 17:34 UTC, beorn7 commented on content/docs/introduction/design-doc.md
> +Design doc dot not always reflect exactly what has been implemented, and
Design doc dot not… → Design docs do not…

2021-06-07 17:34 UTC, beorn7 commented on content/docs/introduction/design-doc.md
> +  <tr><td>TSDB Head Improvements (<a href="document 1">https://docs.google.com/document/d/184urkLQnM7rqLmGvS66I15jU2pyPk_qwd8v_qDlXczo/edit#heading=h.ow34omg0frla</a> - <a href="document 2">https://d
Link text and URL are switched here. (URL needs to be the `href` and "document 1/2"  needs to be the text content of the tag.)

2021-06-07 17:34 UTC, beorn7 commented on content/docs/introduction/design-doc.md
> +  <tr><td><a href="https://docs.google.com/document/d/1oEpjiWfTHF352NCAOGolwij3EIkrprCkdQmaQMpjg4M/edit"></a>First-class network monitoring support in the Prometheus & Grafana ecosystem</td><td>2021-
The `</a>` has to be moved after the title.

2021-06-09 15:36 UTC, beorn7 commented
An now there is the [goreleaser design doc](https://docs.google.com/document/d/16LOT2wK-jntlU-EFADfaEF3YbKH81U9Zl_PvSu4qVwo/edit#heading=h.bupciudrwmna).

List is growing quickly. I guess it makes sense to merge this rather sooner than later so that we all can iterate on it easily.

(But see my syntax remarks above. And my question if we can't just use markdown tables, which would avoid those syntax quirks altogether.)

2021-06-14 18:11 UTC, beorn7 commented
I guess we should also add a TODO entry for reconsidering extrapolation with range selectors (rate/increase/delta) AKA "the (x)rate controversy". At the [dev summit 2020/2](https://docs.google.com/document/d/1vhXKpCNY0k2cbm0g10uM2msXoMoH8CTwrg_dyqsFUKo/edit), we stated: "We want to rethink this from first principles. We will collect our research, thoughts, considerations, and results in 'Prometheus is not feature complete' and discuss at a future dev summit."

I think the topic deserves a fully fledged design doc. I guess we just hadn't developed the habit back then and thought, we could shove it in that existing "Prometheus is not feature complete" document.

2021-06-15 12:46 UTC, beorn7 approved these changes
Looks great.

I'd say, let's merge and iron out any other nits incrementally later.

2021-06-16 12:12 UTC, RichiH requested changes
Minor nits; looks good otherwise, thanks!

2021-06-16 12:12 UTC, RichiH commented on content/docs/introduction/design-doc.md
> +Design doc do not always reflect exactly what has been implemented, and
```suggestion
Design docs do not always reflect exactly what has been implemented, and
```

2021-06-16 12:12 UTC, RichiH commented on content/docs/introduction/design-doc.md
> +docs are not considered documentation.
```suggestion
docs are not considered documentation and can not define a standard.
```

2021-06-16 12:34 UTC, RichiH approved these changes

2021-06-16 12:35 UTC, merged

2021-06-16 12:35 UTC, RichiH commented
Thanks!

2021-06-16 12:36 UTC, roidelapluie commented
> Thanks!

I hated this :)

2021-06-16 12:37 UTC, roidelapluie commented
Note: in my last push, I have used "unbreakable dashes" instead of "dashes" for the dated. It keeps them on the same line in the page, I think it renders better.