Add visualizing metrics using Grafana Tutorial
prometheus/docs pull request #2131
Opened 2022-04-30 10:05 UTC by yolossn

To Do:
- [ ] Change the video links, right now it is in my personal account.

2022-05-17 17:03 UTC, hdost requested changes
Mostly looks good 👍🏼 just a couple of minor suggestions.

2022-05-17 17:03 UTC, hdost commented on content/docs/tutorials/visualizing_metrics_using_grafana.md
> +Enter the URL as `http://localhost:9090` under the HTTP section and click on `Save and Test`.
```suggestion
Enter the URL as [http://localhost:9090](http://localhost:9090) under the HTTP section and click on `Save and Test`.
```

2022-05-23 05:15 UTC, yolossn commented
Made the changes according to the suggestions, Once the files are uploaded ill change the links.

2022-05-23 21:03 UTC, hdost commented
> Made the changes according to the suggestions, Once the files are uploaded ill change the links.

Who needs to upload the videos. Is that something @juliusv can do? If so where do you have the sources for him ti do so?

2022-05-24 06:50 UTC, yolossn commented
@RichiH Uploaded them, have updated the links. @hdost PTAL.

2022-05-25 07:00 UTC, hdost requested changes
Just a couple small touches, that I didn't notice before. 
Looks great though 😊

2022-05-25 07:00 UTC, hdost commented on content/docs/tutorials/visualizing_metrics_using_grafana.md
> +In this tutorial we will create a simple dashboard using [Grafana](https://github.com/grafana/grafana) to visualize the `ping_request_count` metric that we instrumented in the previous tutorial.
For "previous tutorial" i realized we should probably have a link.

2022-05-27 07:07 UTC, merged

2022-05-27 07:07 UTC, RichiH commented
Thanks both of you!