Removed remote-write-receiver allowed values in enable-feature flag
prometheus/docs pull request #2420
Opened 2024-01-22 10:41 UTC by pawarpranav83

The `--enable-feature=remote-write-receiver` flag is deprecated and is going to be removed from Prometheus 3.0 and instead users should use `--web.enable-remote-write-receiver`.

Refs - https://github.com/prometheus/prometheus/issues/13206 https://github.com/prometheus/prometheus/pull/13435

2024-07-05 07:22 UTC, bwplotka requested changes
Yes, but this is a blog post from 2021 and we cannot possibly maintain all old flags ever used in old blog posts (: In fact it might be surprising -- you expect 2021 version of Prometheus to have this feature flag etc.

Thus, I would NOT do this, but thank you for your contribution anyway! What do you think?

2024-10-06 09:36 UTC, Tusenka approved these changes

2024-10-06 13:57 UTC, SuperQ commented
Agreed, we also don't update old blog posts with all of the new flags as well. I don't think we should change this.

2024-10-09 05:48 UTC, Tusenka approved these changes

2026-02-24 15:55 UTC, jan--f commented
Hello from the bug scrub!
Closing as per comments above.

2026-02-24 15:55 UTC, closed without merging